//! Movement profiles: slope-to-speed tables and terrain factors.
//! Implements High-Level Design §4.1b (march tempo) and §5.2 (continuous terrain).
//!
//! Tables are generated by `tools/scripts/tobler_table.py` from Tobler's hiking function,
//! so the simulation only does integer interpolation.

use crate::error::WorldError;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// How one kind of mover crosses ground.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MovementProfile {
    /// `(slope ‰, mm/s)` sample points, ascending by slope.
    pub speed_table: Vec<(i32, i32)>,
    /// Slopes steeper than this, either way, are impassable.
    pub max_abs_slope_permille: i32,
    /// Speed multiplier off roads, ‰.
    pub offroad_factor_permille: i32,
    /// Speed multiplier on a road, ‰, by road condition.
    pub road_factor_permille: BTreeMap<String, i32>,
}

impl MovementProfile {
    /// Linear interpolation in the table; `None` beyond ±`max_abs_slope_permille`
    /// (impassable) or outside the table.
    pub fn base_speed_mm_s(&self, slope_permille: i32) -> Option<i32> {
        if slope_permille.abs() > self.max_abs_slope_permille {
            return None;
        }
        let upper = self
            .speed_table
            .partition_point(|&(s, _)| s < slope_permille);
        let &(s1, v1) = self.speed_table.get(upper)?;
        if s1 == slope_permille {
            return Some(v1);
        }
        let (s0, v0) = self.speed_table.get(upper.checked_sub(1)?).copied()?;
        let (ds, dv) = (i64::from(s1 - s0), i64::from(v1 - v0));
        let v = i64::from(v0) + dv * i64::from(slope_permille - s0) / ds;
        i32::try_from(v).ok()
    }

    /// The fastest base speed in the passable part of the table, mm/s (0 if none).
    pub fn max_speed_mm_s(&self) -> i32 {
        self.speed_table
            .iter()
            .filter(|&&(s, _)| s.abs() <= self.max_abs_slope_permille)
            .map(|&(_, v)| v)
            .max()
            .unwrap_or(0)
    }

    /// Rejects tables the interpolation cannot use: empty, unsorted, or non-positive speeds.
    fn validate(&self, name: &str) -> Result<(), WorldError> {
        let bad = |why: &str| WorldError::Manifest(format!("profile {name}: {why}"));
        if self.speed_table.is_empty() {
            return Err(bad("empty speed table"));
        }
        if self.speed_table.windows(2).any(|w| w[0].0 >= w[1].0) {
            return Err(bad("speed table slopes must be strictly ascending"));
        }
        if self.speed_table.iter().any(|&(_, v)| v <= 0) {
            return Err(bad("speed table speeds must be positive"));
        }
        Ok(())
    }
}

/// Named movement profiles, as loaded from `content/movement/profiles.ron`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProfileSet {
    /// Profiles by name, e.g. `"foot"`.
    pub profiles: BTreeMap<String, MovementProfile>,
}

impl ProfileSet {
    /// Loads and validates a profile file. Extra top-level keys (such as `generated_by`)
    /// are ignored.
    pub fn load(path: &Path) -> Result<Self, WorldError> {
        let text = std::fs::read_to_string(path).map_err(|e| WorldError::Io {
            path: path.display().to_string(),
            message: e.to_string(),
        })?;
        let set: Self = ron::from_str(&text).map_err(|e| WorldError::Manifest(e.to_string()))?;
        for (name, profile) in &set.profiles {
            profile.validate(name)?;
        }
        Ok(set)
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// The shipped `foot` profile.
    pub(crate) fn foot() -> MovementProfile {
        let path =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../content/movement/profiles.ron");
        ProfileSet::load(&path).unwrap().profiles["foot"].clone()
    }

    #[test]
    fn flat_is_1399_and_table_has_61_entries() {
        let p = foot();
        assert_eq!(p.speed_table.len(), 61);
        assert_eq!(p.base_speed_mm_s(0), Some(1399));
    }

    #[test]
    fn interpolates_between_samples() {
        let p = foot();
        assert_eq!(p.base_speed_mm_s(10), Some(1352));
        assert_eq!(p.base_speed_mm_s(-600), Some(243));
        assert_eq!(p.base_speed_mm_s(600), Some(171));
    }

    #[test]
    fn beyond_max_slope_is_impassable() {
        let p = foot();
        assert_eq!(p.base_speed_mm_s(601), None);
        assert_eq!(p.base_speed_mm_s(-601), None);
    }

    #[test]
    fn max_speed_is_downhill_peak() {
        assert_eq!(foot().max_speed_mm_s(), 1609);
    }

    #[test]
    fn unsorted_table_is_rejected() {
        let mut p = foot();
        p.speed_table.swap(0, 1);
        assert!(p.validate("x").is_err());
    }
}
